/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mnCuenta = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenuItem();
        mMantenimiento = new javax.swing.JMenu();
        mnDerivadores = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenuItem();
        mAcciones = new javax.swing.JMenu();
        mnVerDerivador = new javax.swing.JMenuItem();
        mayuda = new javax.swing.JMenu();
        mnAcerdaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal - Derivador GPS");

        mArchivo.setText("Archivo");

        mnCuenta.setText("Cuenta");
        mArchivo.add(mnCuenta);

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mArchivo.add(mnSalir);

        jMenuBar1.add(mArchivo);

        mMantenimiento.setText("Mantenimiento");

        mnDerivadores.setText("Derivadores");
        mnDerivadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDerivadoresActionPerformed(evt);
            }
        });
        mMantenimiento.add(mnDerivadores);

        mnUsuarios.setText("Usuarios");
        mnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuariosActionPerformed(evt);
            }
        });
        mMantenimiento.add(mnUsuarios);

        jMenuBar1.add(mMantenimiento);

        mAcciones.setText("Acciones");
        mAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAccionesActionPerformed(evt);
            }
        });

        mnVerDerivador.setText("Ver Derivadores");
        mnVerDerivador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVerDerivadorActionPerformed(evt);
            }
        });
        mAcciones.add(mnVerDerivador);

        jMenuBar1.add(mAcciones);

        mayuda.setText("Ayuda");

        mnAcerdaDe.setText("Acerca De");
        mayuda.add(mnAcerdaDe);

        jMenuBar1.add(mayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this,"¿Desea salir?","Atención",JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            System.exit(0);
        }
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mAccionesActionPerformed

    private void mnVerDerivadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVerDerivadorActionPerformed
        // TODO add your handling code here:
        frmConsultaDervidador verder = new frmConsultaDervidador();
        verder.setVisible(true);
    }//GEN-LAST:event_mnVerDerivadorActionPerformed

    private void mnDerivadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDerivadoresActionPerformed
        // TODO add your handling code here:
        frmDerivadores dr = new frmDerivadores();
        dr.setVisible(true);
    }//GEN-LAST:event_mnDerivadoresActionPerformed

    private void mnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuariosActionPerformed
        // TODO add your handling code here:
        frmUsuarios usr = new frmUsuarios();
        usr.setVisible(true);
    }//GEN-LAST:event_mnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAcciones;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mMantenimiento;
    private javax.swing.JMenu mayuda;
    private javax.swing.JMenuItem mnAcerdaDe;
    private javax.swing.JMenuItem mnCuenta;
    private javax.swing.JMenuItem mnDerivadores;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnUsuarios;
    private javax.swing.JMenuItem mnVerDerivador;
    // End of variables declaration//GEN-END:variables
}
